### PR TITLE
Implement React Router + Basic File Structure

### PR DESCRIPTION
**Pull request by corneliusrenken**
Added Dependencies:
- React Router

Added routing and file structure for website components.
- Any endpoint that is not specified (/roulette, /scratch-ticket, /slots) will redirect to homepage
- Any endpoint starting with /api will route to our api

### CODE REVIEW

**Comment by corneliusrenken** [comment]
https://trello.com/c/V5cAyw1f/10-m-react-router-implementation-basic-file-structure

**Review by markmiw — APPROVED** [review]
Looks good to me. Thanks

**Comment by BungaloBuce** [comment]
Everything looks great. Keep up the good work!

**Review by BungaloBuce — APPROVED** [review]
Everything looks great. Keep up the good work!

**Pull request merged**
